version: "3.1"

services:
  db:
    image: usersdb/mysql
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password --log_bin_trust_function_creators=1
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: development
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
    ports:
      - 3306:3306
volumes:
  mysql_data: